//local
GET http://localhost:3000/user
###
GET http://localhost:3000/user/68f464fc7bbc542f6fbcd2f3

//create user
###
POST http://localhost:3000/user/ 
content-type: application/json

{
      "username": "BobbetteTheBuilder",
      "email": "IamBobbette@builder.com",
      "firstName": "Bobbette",
      "lastName": "TheBuilder",
      "password": "YesSheCan!"
}

###
DELETE http://localhost:3000/user/68f464fc7bbc542f6fbcd2f3/

//production
###

GET https://randr-9pxd.onrender.com/user
###
GET https://randr-9pxd.onrender.com/user/68f464fc7bbc542f6fbcd2f3

//create user
###
POST https://randr-9pxd.onrender.com/user/ 
content-type: application/json

{
      "username": "BobbetteTheBuilder",
      "email": "IamBobbette@builder.com",
      "firstName": "Bobbette",
      "lastName": "TheBuilder",
      "password": "YesSheCan!"
}